# Generated by Django 4.0 on 2024-04-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Items',
        ),
    ]
