# Generated by Django 4.0 on 2024-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_product_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
