# Generated by Django 4.0 on 2024-04-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0009_itemss_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
